export const ADD_FLATBOOKING = "ADD_FLATBOOKING";
export const RETRIEVE_FLATBOOKING = "RETRIEVE_FLATBOOKING";
export const UPDATE_FLATBOOKING = "UPDATE_FLATBOOKING";
export const DELETE_FLATBOOKING = "DELETE_FLATBOOKING";